version: '3'

services:
    frontend:
        image: coolfan1024/uniboard:0.2.3
        container_name: uniboard-frontend
        ports:
            - '8888:80'
        env_file:
            - .env
        volumes:
            - ./service/media:/usr/share/nginx/media
        depends_on:
            - backend

    backend:
        image: coolfan1024/uniboard-service:0.2.3
        container_name: uniboard-backend
        volumes:
            - ./service/media:/app/media
            - ./service/migrations:/app/api/migrations
        env_file:
            - .env
        depends_on:
            postgres:
                condition: service_healthy
            redis:
                condition: service_healthy

    postgres:
        image: postgres:16.3-bookworm
        container_name: uniboard-postgres
        environment:
            POSTGRES_DB: uniboard
            POSTGRES_PASSWORD: XFdWwID02qJxerertfTrYFiok7G1bg
        env_file:
            - .env
        volumes:
            - ./database/postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U postgres']
            interval: 10s
            timeout: 10s
            retries: 10

    redis:
        image: redis:7.4.0-bookworm
        container_name: uniboard-redis
        command: ['redis-server', '--requirepass', 'GdlkOVEmA3vp8JA6ZoAiqIPxSwZR5']
        env_file:
            - .env
        volumes:
            - ./database/redis_data:/data
        healthcheck:
            test: ['CMD', 'redis-cli', 'ping']
            interval: 3s
            timeout: 3s
            retries: 10
