services:
    web:
        image: coolfan1024/uniboard:latest
        container_name: uniboard-web
        ports:
            - '8888:8080'
        volumes:
            - ./service/media:/app/service
        env_file:
            - .env
        depends_on:
            - db

    db:
        image: postgres:17.4-bookworm
        container_name: uniboard-db
        env_file:
            - .env
        volumes:
            - ./database/postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U postgres']
            interval: 10s
            timeout: 10s
            retries: 10
